version: '2.1'

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      timeout: 5s
      retries: 20
    volumes:
      - 'magento_database:/var/lib/mysql'
  magento:
    # ? Aman: If this image is being used, is it even using the dockerfile from ''./insall'?
    image: 'jamesbrink/magento:2.2-sd'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=root
      - MAGENTO_DATABASE_PASSWORD=password
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_ADMINURI=admin
      - MAGENTO_HOST=local.magento
      - ENABLE_SAMPLE_DATA=true
      - APACHE_LOG_LEVEL=warn
    ports:
      - '80:80'
      - '443:443'
    # volumes:
    #   - ./theme/starter:/magento/htdocs/app/design/frontend/Magento/starter
    depends_on:
      mariadb:
        condition: service_healthy
  # ? Aman: I was trying to add phpmyadmin but was not able to login. Am I not setting the user/password properly above? Or is it not linking properly?
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - mariadb

volumes:
  magento_database:
    driver: local