version: "2.1"

services:
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASES;"'
      timeout: 5s
      retries: 20
    volumes:
      - "magento_database:/var/lib/mysql"
  magento:
    build: ./install
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=root
      - MAGENTO_DATABASE_PASSWORD=password
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_ADMINURI=admin
      - MAGENTO_HOST=94.16.113.25
      - ENABLE_SAMPLE_DATA=true
      - APACHE_LOG_LEVEL=warn
    command: php-fpm
    links:
        - mariadb
    volumes:
      - "./themes:/magento/htdocs/app/design/frontend/Izzi"
      - asset-volume:/mag:rw
    # - './modules:/magento/htdocs/app/code/Izzi'
    depends_on:
      mariadb:
        condition: service_healthy
  # ? How to connect phpmyadmin to the db?
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - asset-volume:/mag:rw
      - ./install/docker-assets/etc/apache2/conf.d/magento.conf:/vhosts/magento.conf:ro
    links: 
      - magento
  cron:
    container_name: crontab
    volumes:
      - asset-volume:/mag:rw
    build: ./install/images/cron
    links:
      - magento

volumes:
  magento_database:
    driver: local
  asset-volume:
    driver: local
