version: "2.1"

services:
  mariadb:
    image: "mariadb:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=password --execute "SHOW DATABASES;"'
      timeout: 5s
      retries: 20
    volumes:
      - "magento_database:/var/lib/mysql"
  magento:
    image: "jamesbrink/magento:2.2-sd"
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MAGENTO_DATABASE_USER=root
      - MAGENTO_DATABASE_PASSWORD=password
      - MAGENTO_DATABASE_NAME=magento
      - MAGENTO_ADMINURI=admin
      - MAGENTO_HOST=local.magento
      - ENABLE_SAMPLE_DATA=true
      - APACHE_LOG_LEVEL=warn
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./themes:/magento/htdocs/app/design/frontend/Izzi"
    # For custom Module development:
    # - './modules:/magento/htdocs/app/code/Izzi'
    depends_on:
      mariadb:
        condition: service_healthy
  # ? How to connect phpmyadmin to the db?
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    links:
      - mariadb

volumes:
  magento_database:
    driver: local
